export const data = [
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
  {
    clientId: "xxxxxxxxx",
    clients: "Client Name",
    country: "Country Name",
    city: "City Name",
    address: "xxxxxxxxx",
    email: "xxxxxxxxxxxx",
    phone: "xxxxxxxx",
    status: "Active",
    amount: "0.00",
  },
];
